### ISSUE TITLE
Feature Proposal: commandline arguments for Plan

### ISSUE THREAD

**Issue by takaoka-youta-opst** [opst/knitfab#21]
Abstract
----------

Commandline arguments are fixed at `docker build`, currently.
But rebuilding to change only arguments are too expensive.

This issue proposes to add declearation of commandline arguments to Plan.

There are 2 options to implementation. I am doubtful which one is more better.

Option1: Fixed arguments
--------------------------

Like below:

```yaml
image: HOST:PORT/REPO/IMAGE:TAG
args: ["--foo", "bar"]

# ...
```

`args` overwrites `CMD` of the image.

### How to receive args as Input

Do like python's `argparse`.

```yaml
image: host:port/repo/some-python-script:v1.0
args: ["--foo", "bar", "@/in/args/argfile"]

inputs:
  - path: "/in/args"
  - tag:
    - "type:args"
    - "project:..."
```

### Pros.

Clear what will be occur.

### Cons.

Static.

Option2: Dynamic args: special input
-----------------------------

Like follow:

```yaml
image: HOST:PORT/REPO/some-script:v1.0
args:
  tags:
    # - "knit#args: true"
    - "key: value"
    - ...
inputs:
  - path: ...
    tags: ...
  - ...
outputs:
  - path: ...
    tags: ...
  - ...
log:
  tags:
    - ...
```

Introduce a new system tag `knit#args`, says "this is commandline args".

`args` property in Plan is a special input. Data which match the tags in `tags` AND `knit#args: true` is passed as args.
Data with `knit#args: true` is a Data has only single file "args" and formatted in "one argument per lines" style.
Knitfab (Projection Loop, maybe) will read the Data contains args and put them as `args` of Container spec of Pod.

### Pros

Dynamic args.

### Cons.

- Introduce specsial Data for args.
- Complexity: event Loop should invokes Data Agent.
