### ISSUE TITLE
Feature Proposal: Input tags constraints with other input tags

### ISSUE THREAD

**Issue by takaoka-youta-opst** [opst/knitfab#25]
# Motivation

Now, Data assigning to Inputs are orthogonal. Knitfab will create Runs for all conbinations for Data and Inputs.

Coupling inputs may be needed. For example,

- An input accepts a training dataset and anothoer accepts its label.
- An input accepts a model and another accepts its metrics.
- An input accepts a training dataset and another accepts the previous dataset.

# Idea

Introduce a new property `filter` for `input` of Plan.

```yaml
inputs:
   - path: /in/data/1
     tags:
     	- "project:..."
     	- "mode: training"
     	- "type: dataset"
   - path: /in/data/2
     tags:
       	- "project:..."
       	- "mode: training"
       	- "type: dataset"
     filter:
       - ref: /in/data/1  # this filter referes input with path "/in/data/1"
         match:
           - "==series"  # requries having a tag keyed "series" and its value is same as Data assinged "/in/data/1" having.
           - "2d <= knit#timestamp < 1d"  #  tag "knit#timestmap" is in a range relatively Data assigned "/in/data/1"
    - path: /in/data/3
      tags:
     	- "project:..."
     	- "mode: training"
     	- "type: dataset"
      filter:
        - ref: /in/data/2
          match:
           - "==series"
           - "2d <= knit#timestamp < 1d"
```

Exampel above says "use Data for 3 days from /in/data/1". If Data are collected once per day, this means continual training with a sliding windowed dataset.

# Probrem

How should filtered out Run be handled?
 Tags on Data can be changed. If conditions are met, Runs which was filtered out once may be needed to do.
