### ISSUE TITLE
Feature Proposal: Sideeffect of Run to change Tags on Data assigned to Input

### ISSUE THREAD

**Issue by takaoka-youta-opst** [opst/knitfab#26]
# Motivation

Think about competing models, "challenger" and "champion". `champion` is deploied in production environment now, and "challenger" is a new model based a recent continual training.

When a Run compairing the 2 models, now we can

- create a copy of the winner.
- set Tag like "tier: champion" to the copy of winner model.

But, doing that is leads confusing state. If "challenger" won, 2 models have "model: champion" tag. And, dead-copy of the winner model will be created.

If Tags on Data assigned Inputs can be updated at the end of Run, the probrem will be solved.

- Run comparing "challenger" and "champion" will success when "challenger" wins.
- When Run get be "done" status, remove "tier: champion" from it was, and put it to new winner

# Idea

Introduce a new property `sideeffect` to Input.

```yaml
inputs:
  - path: "/work/in/model/challenger/"
   tags:
     - "project:test"
     - "type:model"
     - "tier:challenger"
   sideeffect:
     on_done:
       add_tag:  # these tags are added to Data assigned this input when the Run get be "done"
         - "tier:champion"
       remove_tag:  # these tags are removed to Data assigned this input when the Run get be "done"
         - "tier:challenger"
  - path: "/work/in/model/champion/"
   tags:
     - "project:test"
     - "type:model"
     - "tier:champion"
   sideeffect:
     on_done:
       add_tag:
       - "tier:ex-champion"
       remove_tag:
         - "tier:champion"
```

# Probrem

Take care not to create cyclic dependency by sideeffects.
