### ISSUE TITLE
Addon with WebAPI

### ISSUE THREAD

**Issue by takaoka-youta-opst** [opst/knitfab#52]
# Motivation

To be able to add extra APIs coming from addons, allow extend WebAPI of knitd.

# Spec

Reserve a path `/api/x/` for extra APIs.

In the config file, declare extra APIs like

```yaml
extraApi:
  foo: https://example.com/foo
  bar: https://example.com/bar
```

Then, any requests `/api/x/foo/...` will be proxied to `https://example.com/foo/...` .

**Comment by takaoka-youta-opst** [comment]
The format of configuration file is changed from at the first of this issue.

Now we are doing as below:

```yaml
extraApis:
  endpoints:
    - path: ...
      proxy_to: ...
    ...
```

and, `knitd` proxies requests received on pathes as `path` in a `endpoints` entry to corresponding `proxy_to` URL.
